  arj a fin_cop tran_opl.dbf bk.dbf avot.dbf osdkom.dbf unin.mem
  copy d:\fin_otd\ttnf.dbf d:\arm\finr\cop\ttnf.dbf
  copy d:\arm\finr\fin_cop.arj d:\arm\finr\cop
  copy d:\arm\finr\fin_cop.arj a:\fin_cop.arj
  erase d:\arm\finr\fin_cop.arj
  copy d:\arm_t\finr\bk.dbf d:\arm_t\cop\bk.dbf
  copy d:\fin_otd\ttnf.dbf f:\work\fin\ttnf.dbf
  copy d:\arm\finr\*.* f:\work\fin\cop
  copy f:\work\sklad\ttnf.txt f:\work\fin\ttnf.txt
  copy f:\work\sklad\ttnf.txt f:\work\fin\ttnf2.txt
  erase f:\work\sklad\ttnf.txt