#0
Игнорируется таблица набора символов из файла...

#1
Набор символов

#2
Невозможно найти набор символов в файле таблиц

#3
Невозможно открыть для записи порт принтера

#4
Генерируется набор символов; это потребует некоторого времени...

#5
Управляющие символы принтера

#6
Составные математические символы

#7
Составные символы линейной графики

#8
Генератор набора символов фирмы "Хьюлетт-Паккард"

#9
Версия 1.0

#10
Copyright(c) 1994 Hewlett-Packard

#11
Синтаксис: SYMSETS <Номер_набора_символов> <Выход> [-i]

Эта программа печатает таблицы набора символов, заданного 
уникальным идентификатором этого набора (SymbolSetID). Если 
в принтере HP LaserJet нет этого набора символов, будет 
использован набор символов, принятый в данном принтере 
по умолчанию. Чтобы распечатать набор символов, отсутствующий 
в файле таблиц SYMSETS.TBL, введите в команду параметр -i. 
Список наборов символов приведен в файле SYMSETS.TXT. 
Ниже показан пример команды, которую нужно ввести на запрос DOS, 
чтобы вывести через порт принтера LPT1: таблицы набора символов 
Wingdings:

	   SYMSETS  579L LPT1
